### ISSUE TITLE
Update Python versions - Python 3.13

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/x-wr-timezone#15]
Python 3.13 has been released.

Please

- [ ] add the Python version and tests
- [ ] document which files to touch on a Python version change below the release section in the README.md file
- [ ] make sure all other Python versions are alright

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/x-wr-timezone/issues/15">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/x-wr-timezone/issues/15/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/x-wr-timezone/issues/15/pledge.svg">
</picture>
</a>

**Comment by Brijeshthummar02** [comment]
i can work on it, assign me to the task.

**Comment by niccokunzmann** [comment]
Hi, thanks! You are welcome to work on this, please open a pull request!

**Comment by niccokunzmann** [comment]
Thanks @Brijeshthummar02 for solving this! Good luck on your next PRs!
