### ISSUE TITLE
Remove pytz dependency

### ISSUE THREAD

**Issue by NicoHood** [niccokunzmann/x-wr-timezone#2]
I suggest to use the python builtin `ZoneInfo` object instead.

**Comment by niccokunzmann** [comment]
Yep, you can do that. I think icalendar has pytz as dependency. As such, it cannot be completely removed. What do you think?

Am 14. Januar 2022 14:08:40 GMT+00:00 schrieb NicoHood ***@***.***>:

**Comment by NicoHood** [comment]
I am not sure, but didnt they want to remove that dependency as well?

**Comment by niccokunzmann** [comment]
Is there a link for their issue?

**Comment by NicoHood** [comment]
It does not seem to support it for now:
https://github.com/collective/icalendar/issues/333

**Comment by niccokunzmann** [comment]
I will close this for now. When icalendar Updates its dependecies, we can open it again.
